version: "3.9"

networks:
  app:
    driver: bridge
    ipam:
      config:
        - subnet: ${IP_SUBNET}
          gateway: ${IP_GATEWAY}

services:
  selenium:
    container_name: "${PROJECT_NAME}-selenium"
    image: selenium/standalone-chrome:4.7.0
    restart: unless-stopped
    shm_size: 2gb
    networks:
      app:
        ipv4_address: ${SELENIUM_IP}
    ports:
      - "4444:4444"
      - "7900:7900"

  fpm:
    container_name: "${PROJECT_NAME}-fpm"
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./docker/php/fpm/Dockerfile
    volumes:
      - ${SRC_PATH}/app:/var/www/php/app:rw
      - ${SRC_PATH}/composer.json:/var/www/php/composer.json:rw
      - ${SRC_PATH}/composer.lock:/var/www/php/composer.lock:rw
      - ${SRC_PATH}/vendor:/var/www/php/vendor:rw

      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/php/fpm/pool.d/app.conf:/usr/local/etc/php-fpm.d/app.conf:ro

      - ./docker/data/socket:/var/run:rw

      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/hosts:/etc/hosts:ro
    environment:
      USER_ID: 1000
      GROUP_ID: 1000
      PHP_IDE_CONFIG: "serverName=${PHP_IDE_CONFIG}"
    networks:
      app:
        ipv4_address: ${FPM_IP}
    ports:
      - "9000:9000"

  cli:
    container_name: "${PROJECT_NAME}-cli"
    build:
      context: ./docker/php/cli
      args:
        SUPERCRONIC_VERSION: "0.1.12"
        SUPERCRONIC_SHA1SUM: "048b95b48b708983effb2e5c935a1ef8483d9e3e"
        APP_PATH: /var/www/php
    restart: unless-stopped
    stdin_open: true
    volumes:
      - ${SRC_PATH}/app:/var/www/php/app:rw
      - ${SRC_PATH}/composer.json:/var/www/php/composer.json:rw
      - ${SRC_PATH}/composer.lock:/var/www/php/composer.lock:rw
      - ${SRC_PATH}/vendor:/var/www/php/vendor:rw

      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/cron/crontab:/etc/crontabs/crontab:rw

      - ./docker/data/socket:/var/run:rw

      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/hosts:/etc/hosts:ro
    networks:
      app:
        ipv4_address: ${CLI_IP}

  nginx:
    container_name: "${PROJECT_NAME}-nginx"
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ${SRC_PATH}:/var/www/php:rw

      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro

      - ./docker/data/tmp/nginx:/var/cache/nginx:rw
      - ./docker/data/socket:/var/run:rw

      - ./docker/logs/nginx:/var/log/nginx:rw
    ports:
      - ${NGINX_PORT}
    networks:
      app:
        ipv4_address: ${NGINX_IP}